<?php 

class CargaExcel
{

function LiberarTotal($usuario)
{
$SQL="DELETE FROM [022BDCOMUN].DBO.DATOS_RSV  WHERE  USUARIO='$usuario'";
$RESULT=mssql_query($SQL);
if (!$SQL) 
{
echo"<script>
alert('Error al Eliminar');
window.location='/reserva/consulta/carga-excel';
</script>";
}

else
{
header('Location: /reserva/pages/cargar');
}
}


function LiberarItem($usuario,$codigo)
{
$SQL="DELETE FROM [022BDCOMUN].DBO.DATOS_RSV  WHERE  USUARIO='$usuario' AND 
CODIGO='$codigo'";
$RESULT=mssql_query($SQL);
if (!$SQL) 
{
echo"<script>
alert('Error al Eliminar');
window.location='/reserva/consulta/carga-excel';
</script>";
}

else
{
header('Location: /reserva/consulta/carga-excel');
}
}


function Registrar($usuario,$reserva)
{

$link=Conectarse();
$SQLreserva="INSERT INTO [022BDCOMUN].DBO.RESERVA_DET(NRORESERVA,CODIGO,CANTIDAD,CANT_PEND)
(SELECT $reserva,DRV.CODIGO,DRV.CANTIDAD,DRV.CANTIDAD
FROM [022BDCOMUN].DBO.DATOS_RSV AS DRV LEFT JOIN 
[022BDCOMUN].DBO.RESERVA_DET AS D ON 
DRV.CODIGO=D.CODIGO  LEFT JOIN [010BDCOMUN].DBO.STKART AS S ON 
DRV.CODIGO=S.STCODIGO AND STALMA='01' LEFT JOIN [010BDCOMUN].DBO.MAEART AS M ON
DRV.CODIGO=M.ACODIGO  WHERE USUARIO='$usuario'   AND
M.AFSTOCK='S' AND STALMA='01' AND AESTADO='V'
GROUP BY DRV.CODIGO,M.ADESCRI,DRV.CANTIDAD,DRV.TIPO,M.AUNIDAD,S.STSKDIS
HAVING ISNULL(S.STSKDIS,0)-SUM(ISNULL(D.CANT_PEND,0))>=DRV.CANTIDAD  AND  
ISNULL(S.STSKDIS,0)-SUM(ISNULL(D.CANT_PEND,0))<>0  AND ISNULL(S.STSKDIS,0)-SUM(ISNULL(D.CANT_PEND,0))>=1)
UNION
(SELECT $reserva,DRV.CODIGO,(ISNULL(S.STSKDIS,0)-SUM(ISNULL(D.CANT_PEND,0))),
(ISNULL(S.STSKDIS,0)-SUM(ISNULL(D.CANT_PEND,0))) 
FROM [022BDCOMUN].DBO.DATOS_RSV AS DRV LEFT JOIN 
[022BDCOMUN].DBO.RESERVA_DET AS D ON 
DRV.CODIGO=D.CODIGO  LEFT JOIN [010BDCOMUN].DBO.STKART AS S ON 
DRV.CODIGO=S.STCODIGO AND STALMA='01' LEFT JOIN [010BDCOMUN].DBO.MAEART AS M ON
DRV.CODIGO=M.ACODIGO  WHERE USUARIO='$usuario'   AND
M.AFSTOCK='S' AND STALMA='01' AND AESTADO='V'
GROUP BY DRV.CODIGO,M.ADESCRI,DRV.CANTIDAD,DRV.TIPO,M.AUNIDAD,S.STSKDIS
HAVING  (ISNULL(S.STSKDIS,0)-SUM(ISNULL(D.CANT_PEND,0))) < DRV.CANTIDAD  AND
(ISNULL(S.STSKDIS,0)-SUM(ISNULL(D.CANT_PEND,0))) <>0)";


$SQLprerq="INSERT INTO [022BDCOMUN].dbo.PRE_REQUISD(CODIGOPRE_REQUISD,CANTPRE_REQUISD,USUARIO,TIPOPRE_REQUISD,OT,CENTROCOSTO)
(SELECT DRV.CODIGO,DRV.CANTIDAD-(ISNULL(S.STSKDIS,0)-SUM(ISNULL(D.CANT_PEND,0))),'$usuario','RQ','',''
FROM [022BDCOMUN].DBO.DATOS_RSV AS DRV LEFT JOIN 
[022BDCOMUN].DBO.RESERVA_DET AS D ON 
DRV.CODIGO=D.CODIGO  LEFT JOIN [010BDCOMUN].DBO.STKART AS S ON 
DRV.CODIGO=S.STCODIGO AND STALMA='01' LEFT JOIN [010BDCOMUN].DBO.MAEART AS M ON
DRV.CODIGO=M.ACODIGO  WHERE USUARIO='$usuario'   AND
M.AFSTOCK='S' AND STALMA='01' AND AESTADO='V'
GROUP BY DRV.CODIGO,M.ADESCRI,DRV.CANTIDAD,DRV.TIPO,M.AUNIDAD,S.STSKDIS
HAVING  (ISNULL(S.STSKDIS,0)-SUM(ISNULL(D.CANT_PEND,0))) < DRV.CANTIDAD  AND
(ISNULL(S.STSKDIS,0)-SUM(ISNULL(D.CANT_PEND,0))) <>0)
UNION
(SELECT DRV.CODIGO,DRV.CANTIDAD,'$usuario','RQ','',''
FROM [022BDCOMUN].DBO.DATOS_RSV AS DRV LEFT JOIN 
[022BDCOMUN].DBO.RESERVA_DET AS D ON 
DRV.CODIGO=D.CODIGO  LEFT JOIN [010BDCOMUN].DBO.STKART AS S ON 
DRV.CODIGO=S.STCODIGO AND STALMA='01' LEFT JOIN [010BDCOMUN].DBO.MAEART AS M ON
DRV.CODIGO=M.ACODIGO  WHERE USUARIO='$usuario'   AND
M.AFSTOCK='S' AND STALMA='01' AND AESTADO='V'
GROUP BY DRV.CODIGO,M.ADESCRI,DRV.CANTIDAD,DRV.TIPO,M.AUNIDAD,S.STSKDIS
HAVING (ISNULL(S.STSKDIS,0)-SUM(ISNULL(D.CANT_PEND,0)))=0)";

$SQLliberar="DELETE FROM  [022BDCOMUN].dbo.DATOS_RSV  WHERE USUARIO='$usuario'";


$RESULTprerq=mssql_query($SQLprerq);

if (!$RESULTprerq)
{
echo "error al registrar";
}

else

{
$RESULTreserva=mssql_query($SQLreserva);
$RESULTliberar=mssql_query($SQLliberar);

echo "<script>
window.location='/reserva/pages/editar-reserva?id=$reserva';
 </script>";
}


}



function LimpiarData($usuario)
{
$link=Conectarse();
$SQL="DELETE FROM [022BDCOMUN].DBO.DATOS_RSV  WHERE  USUARIO='$usuario'";

$SQLliberarprerq="DELETE FROM  [022BDCOMUN].dbo.PRE_REQUISD  WHERE USUARIO='$usuario'";

$RESULT=mssql_query($SQL);
if (!$RESULT) 
{
echo"<script>
alert('Error al limpiar');
window.location='/reserva/home';
</script>";
}

else
{
$RESULTliberarprerq=mssql_query($SQLliberarprerq);
header('Location: /reserva/pages/cargar');
}

}


}


?>