<?php 

class Ni
{

function TransferirReserva($reserva,$ni)
{

$link=Conectarse();

$SQL="INSERT INTO [022BDCOMUN].dbo.RESERVA_DET
(NRORESERVA,CODIGO,CANTIDAD,CANT_PEND,ITEM,DESCRIPCION,NUMERO_DOC,UNIDAD)
SELECT '$reserva',M.DECODIGO,M.DECANTID,M.DECANTID,M.DEITEM,MA.ADESCRI,M.DENUMDOC,
M.DEUNIDAD
FROM [010BDCOMUN].dbo.MOVALMDET as M INNER JOIN [010BDCOMUN].DBO.MAEART AS MA 
ON M.DECODIGO=MA.ACODIGO  WHERE M.DENUMDOC='$ni' AND M.DETD='NI'";

$SQL1="UPDATE [022BDCOMUN].DBO.RESERVA_DET SET 
CANT_PEND=RD.CANTIDAD-D.DECANTID
FROM [010BDCOMUN].DBO.MOVALMCAB AS C 
INNER JOIN [010BDCOMUN].DBO.MOVALMDET AS D ON
C.CANUMDOC=D.DENUMDOC AND CANUMDOC='$ni'AND  CATD='NI' AND DETD='NI'
  INNER JOIN [022BDCOMUN].DBO.RESERVA_DET  AS RD 
ON D.DECODIGO=RD.CODIGO AND D.DENUMDOC=RD.NUMERO_DOC AND NRORESERVA='1' ";

$SQL2="INSERT INTO [022BDCOMUN].DBO.DOCUMENTO VALUES('$ni','A')";

$RESULT=mssql_query($SQL);
if (!$RESULT) 
{
  echo "error";
}

else

{
  $RESULT1=mssql_query($SQL1);
  $RESULT2=mssql_query($SQL2);

 header('Location: /reserva/pages/editar-reserva?id='.$reserva);
}



}


}

 ?>